Repository atlassian/data-center-helm-charts, pull requests merged in 2022-01, with the labels that each got.

#341 Define podAnnotations as template to allow overrides
  src/main/charts/bamboo-agent/templates/_helpers.tpl
  src/main/charts/bamboo-agent/templates/deployment-agent.yaml
  src/main/charts/bamboo/templates/_helpers.tpl
  src/main/charts/bamboo/templates/statefulset.yaml
  src/main/charts/bamboo/templates/tests/test-application-status.yaml
  src/main/charts/bamboo/templates/tests/test-database-connectivity.yaml
  src/main/charts/bamboo/templates/tests/test-shared-home-permissions.yaml
  src/main/charts/bitbucket/templates/_helpers.tpl
  src/main/charts/bitbucket/templates/statefulset.yaml
  src/main/charts/bitbucket/templates/tests/test-application-status.yaml
  src/main/charts/bitbucket/templates/tests/test-database-connectivity.yaml
  src/main/charts/bitbucket/templates/tests/test-shared-home-permissions.yaml
  src/main/charts/confluence/templates/_helpers.tpl
  src/main/charts/confluence/templates/statefulset-synchrony.yaml
  src/main/charts/confluence/templates/statefulset.yaml
  src/main/charts/confluence/templates/tests/test-application-status.yaml
  src/main/charts/confluence/templates/tests/test-database-connectivity.yaml
  src/main/charts/confluence/templates/tests/test-shared-home-permissions.yaml
  src/main/charts/crowd/templates/_helpers.tpl
  src/main/charts/crowd/templates/nfs-permission-fixer.yaml
  src/main/charts/crowd/templates/statefulset.yaml
  src/main/charts/crowd/templates/tests/test-application-status.yaml
  src/main/charts/crowd/templates/tests/test-shared-home-permissions.yaml
  src/main/charts/jira/templates/_helpers.tpl
  src/main/charts/jira/templates/statefulset.yaml
  src/main/charts/jira/templates/tests/test-application-status.yaml
  src/main/charts/jira/templates/tests/test-database-connectivity.yaml
  src/main/charts/jira/templates/tests/test-shared-home-permissions.yaml
  src/test/java/test/PodAnnotationsTest.java
  src/test/java/test/model/Deployment.java
Labels: enhancement, community

#365 add feature to define loadBalancerIP
  src/main/charts/bamboo/README.md
  src/main/charts/bamboo/templates/service.yaml
  src/main/charts/bamboo/values.yaml
  src/main/charts/bitbucket/README.md
  src/main/charts/bitbucket/templates/service-ssh.yaml
  src/main/charts/bitbucket/templates/service.yaml
  src/main/charts/bitbucket/values.yaml
  src/main/charts/confluence/README.md
  src/main/charts/confluence/templates/service-synchrony.yaml
  src/main/charts/confluence/templates/service.yaml
  src/main/charts/confluence/values.yaml
  src/main/charts/crowd/README.md
  src/main/charts/crowd/templates/service.yaml
  src/main/charts/crowd/values.yaml
  src/main/charts/jira/README.md
  src/main/charts/jira/templates/service.yaml
  src/main/charts/jira/values.yaml
  src/test/java/test/ServiceTest.java
  src/test/java/test/model/Service.java
Labels: community

#366 BAMBK8S-172: Remove 'under active development' references
  docs/docs/README.md
  docs/docs/troubleshooting/LIMITATIONS.md
Labels: documentation, Bamboo, 1st release

#364 add new feature podLabels
  src/main/charts/bamboo-agent/README.md
  src/main/charts/bamboo-agent/templates/_helpers.tpl
  src/main/charts/bamboo-agent/templates/deployment-agent.yaml
  src/main/charts/bamboo-agent/values.yaml
  src/main/charts/bamboo/README.md
  src/main/charts/bamboo/templates/_helpers.tpl
  src/main/charts/bamboo/templates/statefulset.yaml
  src/main/charts/bamboo/values.yaml
  src/main/charts/bitbucket/README.md
  src/main/charts/bitbucket/templates/_helpers.tpl
  src/main/charts/bitbucket/templates/statefulset.yaml
  src/main/charts/bitbucket/values.yaml
  src/main/charts/confluence/README.md
  src/main/charts/confluence/templates/_helpers.tpl
  src/main/charts/confluence/templates/statefulset-synchrony.yaml
  src/main/charts/confluence/templates/statefulset.yaml
  src/main/charts/confluence/values.yaml
  src/main/charts/crowd/README.md
  src/main/charts/crowd/templates/_helpers.tpl
  src/main/charts/crowd/templates/statefulset.yaml
  src/main/charts/crowd/values.yaml
  src/main/charts/jira/README.md
  src/main/charts/jira/templates/_helpers.tpl
  src/main/charts/jira/templates/statefulset.yaml
  src/main/charts/jira/values.yaml
  src/test/java/test/PodTest.java
  src/test/java/test/model/StatefulSet.java
Labels: community

#334 add new feature additionalVolumeClaimTemplates
  src/main/charts/bamboo/README.md
  src/main/charts/bamboo/templates/_helpers.tpl
  src/main/charts/bamboo/values.yaml
  src/main/charts/bitbucket/README.md
  src/main/charts/bitbucket/templates/_helpers.tpl
  src/main/charts/bitbucket/values.yaml
  src/main/charts/confluence/README.md
  src/main/charts/confluence/templates/_helpers.tpl
  src/main/charts/confluence/values.yaml
  src/main/charts/crowd/README.md
  src/main/charts/crowd/templates/_helpers.tpl
  src/main/charts/crowd/values.yaml
  src/main/charts/jira/README.md
  src/main/charts/jira/templates/_helpers.tpl
  src/main/charts/jira/values.yaml
  src/test/java/test/VolumesTest.java
Labels: community

#363 [Suggestion] - Add service account annotation
  src/main/charts/bamboo-agent/README.md
  src/main/charts/bamboo-agent/templates/serviceaccount.yaml
  src/main/charts/bamboo-agent/values.yaml
  src/main/charts/bamboo/README.md
  src/main/charts/bamboo/templates/serviceaccount.yaml
  src/main/charts/bamboo/values.yaml
  src/main/charts/bitbucket/README.md
  src/main/charts/bitbucket/templates/serviceaccount.yaml
  src/main/charts/bitbucket/values.yaml
  src/main/charts/confluence/README.md
  src/main/charts/confluence/templates/serviceaccount.yaml
  src/main/charts/confluence/values.yaml
  src/main/charts/crowd/README.md
  src/main/charts/crowd/templates/serviceaccount.yaml
  src/main/charts/crowd/values.yaml
  src/main/charts/jira/README.md
  src/main/charts/jira/templates/serviceaccount.yaml
  src/main/charts/jira/values.yaml
  src/test/java/test/ServiceAccountTest.java
  src/test/java/test/ServiceTest.java
  src/test/java/test/model/KubeResource.java
Labels: community

#370 Update ingress architecture diagram
  docs/docs/assets/images/ingress.png
  docs/docs/assets/images/ingress.xml
Labels: documentation
