Repository atlassian/data-center-helm-charts, pull requests merged in 2023-07, with the labels that each got.

#616 Unset default limits for Confluence
  src/main/charts/confluence/values.yaml
  src/test/java/test/RequestsTest.java
  src/test/resources/expected_helm_output/confluence/output.yaml
Labels: e2e

#619 CLIP-1817: Add additionalVolumes and additionalVolumeMounts to bamboo-agent
  src/main/charts/bamboo-agent/README.md
  src/main/charts/bamboo-agent/templates/_helpers.tpl
  src/main/charts/bamboo-agent/templates/deployment-agent.yaml
  src/main/charts/bamboo-agent/values.yaml
  src/test/java/test/VolumesTest.java
  src/test/resources/expected_helm_output/bamboo-agent/output.yaml
Labels: e2e

#622 make sharedHome.permissionFix.command helper to be per-product
  docs/docs/examples/external_libraries/EXTERNAL_LIBS.md
  src/main/charts/bamboo/templates/_helpers.tpl
  src/main/charts/bamboo/templates/statefulset.yaml
  src/main/charts/bitbucket/templates/_helpers.tpl
  src/main/charts/bitbucket/templates/statefulset.yaml
  src/main/charts/confluence/templates/_helpers.tpl
  src/main/charts/confluence/templates/statefulset.yaml
  src/main/charts/crowd/templates/_helpers.tpl
  src/main/charts/crowd/templates/statefulset.yaml
  src/main/charts/jira/templates/_helpers.tpl
  src/main/charts/jira/templates/statefulset.yaml
Labels: e2e, kind

#625 Add additionalFiles to bamboo-agent Helm chart
  src/main/charts/bamboo-agent/README.md
  src/main/charts/bamboo-agent/templates/deployment-agent.yaml
  src/main/charts/bamboo-agent/values.yaml
  src/test/java/test/AdditionalFilesTest.java
Labels: e2e

#623 Support running Jira and Confluence containers as non root (incl running in OpenShift)
  docs/docs/platforms/OPENSHIFT.md
  src/main/charts/confluence/README.md
  src/main/charts/confluence/templates/_helpers.tpl
  src/main/charts/confluence/templates/configmap-server-config.yaml
  src/main/charts/confluence/values.yaml
  src/main/charts/jira/README.md
  src/main/charts/jira/templates/_helpers.tpl
  src/main/charts/jira/templates/configmap-server-config.yaml
  src/main/charts/jira/values.yaml
  src/test/java/test/ServerConfigTest.java
Labels: e2e, kind

#626 CLIP-1786: Add liveness probes, make readinessProbes configurable
  src/main/charts/bamboo-agent/README.md
  src/main/charts/bamboo/README.md
  src/main/charts/bamboo/templates/statefulset.yaml
  src/main/charts/bamboo/values.yaml
  src/main/charts/bitbucket/README.md
  src/main/charts/bitbucket/templates/statefulset.yaml
  src/main/charts/bitbucket/values.yaml
  src/main/charts/confluence/README.md
  src/main/charts/confluence/templates/statefulset.yaml
  src/main/charts/confluence/values.yaml
  src/main/charts/crowd/README.md
  src/main/charts/crowd/templates/statefulset.yaml
  src/main/charts/crowd/values.yaml
  src/main/charts/jira/README.md
  src/main/charts/jira/templates/statefulset.yaml
  src/main/charts/jira/values.yaml
  src/test/java/test/ReadinessLivenessProbesTest.java
  src/test/resources/expected_helm_output/bamboo-agent/output.yaml
  src/test/resources/expected_helm_output/bamboo/output.yaml
  src/test/resources/expected_helm_output/bitbucket/output.yaml
  src/test/resources/expected_helm_output/confluence/output.yaml
  src/test/resources/expected_helm_output/crowd/output.yaml
  src/test/resources/expected_helm_output/jira/output.yaml
Labels: e2e

#630 Disable liveness probes by default, make timeoutSeconds configurable
  src/main/charts/bamboo/README.md
  src/main/charts/bamboo/templates/statefulset.yaml
  src/main/charts/bamboo/values.yaml
  src/main/charts/bitbucket/README.md
  src/main/charts/bitbucket/templates/statefulset.yaml
  src/main/charts/bitbucket/values.yaml
  src/main/charts/confluence/README.md
  src/main/charts/confluence/templates/statefulset.yaml
  src/main/charts/confluence/values.yaml
  src/main/charts/crowd/README.md
  src/main/charts/crowd/templates/statefulset.yaml
  src/main/charts/crowd/values.yaml
  src/main/charts/jira/README.md
  src/main/charts/jira/templates/statefulset.yaml
  src/main/charts/jira/values.yaml
  src/test/java/test/ReadinessLivenessProbesTest.java
  src/test/resources/expected_helm_output/bamboo-agent/output.yaml
  src/test/resources/expected_helm_output/bamboo/output.yaml
  src/test/resources/expected_helm_output/bitbucket/output.yaml
  src/test/resources/expected_helm_output/confluence/output.yaml
  src/test/resources/expected_helm_output/crowd/output.yaml
  src/test/resources/expected_helm_output/jira/output.yaml
Labels: kind
