Repository atlassian/data-center-helm-charts, pull requests merged in 2023-06, with the labels that each got.

#572 DCCLIP-492: Documentation for monitoring
  docs/docs/assets/images/grafana_dashboards/filter_by_tag.png
  docs/docs/examples/monitoring/PROMETHEUS.md
  docs/docs/userguide/.pages
  docs/docs/userguide/OPERATION.md
  docs/docs/userguide/monitoring/.pages
  docs/docs/userguide/monitoring/PRE_CANNED_CHARTS.md
  docs/docs/userguide/monitoring/PROMETHEUS.md
  docs/mkdocs.yml
Labels: documentation

#602 fix: swap ingress paths for priority based rules
  src/main/charts/confluence/templates/ingress.yaml
Labels: e2e

#608 Run jmx init container as root: get fix from common chart ver 1.2.3
  src/main/charts/bamboo-agent/Chart.lock
  src/main/charts/bamboo-agent/Chart.yaml
  src/main/charts/bamboo/Chart.lock
  src/main/charts/bamboo/Chart.yaml
  src/main/charts/bitbucket/Chart.lock
  src/main/charts/bitbucket/Chart.yaml
  src/main/charts/confluence/Chart.lock
  src/main/charts/confluence/Chart.yaml
  src/main/charts/crowd/Chart.lock
  src/main/charts/crowd/Chart.yaml
  src/main/charts/jira/Chart.lock
  src/main/charts/jira/Chart.yaml
  src/test/resources/expected_helm_output/bamboo/output.yaml
  src/test/resources/expected_helm_output/bitbucket/output.yaml
  src/test/resources/expected_helm_output/confluence/output.yaml
  src/test/resources/expected_helm_output/crowd/output.yaml
  src/test/resources/expected_helm_output/jira/output.yaml
Labels: kind
